CREATE DATABASE BIBLIOTECA_DB;

use BIBLIOTECA_DB;

CREATE TABLE Autor (
	Codigo_Autor VARCHAR PRIMARY KEY NOT NULL,
	Nombres VARCHAR NOT NULL,
	Apellidos VARCHAR NOT NULL
);

CREATE TABLE Biblioteca (
	ID_Bliblioteca INT PRIMARY KEY NOT NULL,
	Facultad VARCHAR NOT NULL
);

CREATE TABLE Pais (
	ID_Pais INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR NOT NULL
);

CREATE TABLE Libro (
	ID_libro INT PRIMARY KEY NOT NULL,
	Titulo  VARCHAR NOT NULL,
	Codigo_Autor VARCHAR NOT NULL FOREIGN KEY REFERENCES Autor(Codigo_Autor),
	Cantidad INT NOT NULL,
	Contenido  VARCHAR NOT NULL,
	ID_Bliblioteca  INT NOT NULL FOREIGN KEY REFERENCES Biblioteca(ID_Bliblioteca),
	ID_Pais INT NOT NULL FOREIGN KEY REFERENCES Pais(ID_Pais)
);


CREATE TABLE Tipo_Lector (
	ID_Tipo_Lector INT PRIMARY KEY NOT NULL,
	Tipo VARCHAR NOT NULL
);

CREATE TABLE Lector (
	ID_Lector INT PRIMARY KEY NOT NULL,
	ID_Tipo_Lector INT NOT NULL FOREIGN KEY REFERENCES Tipo_Lector(ID_Tipo_Lector),
	Usuario VARCHAR NOT NULL
);


CREATE TABLE EstadoPrestamo (
	ID_EstadoPrestamo INT PRIMARY KEY NOT NULL,
	EstadoPrestamo VARCHAR NOT NULL
);


CREATE TABLE Prestamo (
	ID_Prestamo INT PRIMARY KEY NOT NULL,
	ID_Libro INT NOT NULL FOREIGN KEY REFERENCES Libro(ID_Libro),
	ID_Lector INT NOT NULL FOREIGN KEY REFERENCES Lector(ID_Lector),
	FechaPrestamo DATE NOT NULL,
	FechaEntrega DATE NOT NULL,
	ID_Estado_prestamo INT NOT NULL FOREIGN KEY REFERENCES EstadoPrestamo(ID_EstadoPrestamo)
);

CREATE TABLE Valoracion (
	ID_Valoracion INT PRIMARY KEY NOT NULL,
	ID_Libro INT NOT NULL FOREIGN KEY REFERENCES Libro(ID_Libro),
	ID_Lector INT NOT NULL FOREIGN KEY REFERENCES Lector(ID_Lector),
	Valoracion INT NOT NULL
);

CREATE TABLE Existencias (
	ID_Existencia INT PRIMARY KEY NOT NULL,
	ID_Libro INT NOT NULL FOREIGN KEY REFERENCES Libro(ID_Libro),
	Estado_Existencia VARCHAR NOT NULL,
	Fecha_Adquisicion DATE NOT NULL
);

